name: Go-hello-world

on: [push, pull_request]

jobs:

  build:
    name: e2e-kind-hello-world
    runs-on: ubuntu-latest
    if: >
      (( github.event.pull_request.head.repo.owner.login != github.event.pull_request.base.repo.owner.login ) &&
        github.event_name == 'pull_request' ) || (github.event_name == 'push' && github.event.commits != '[]' )
    env:
      GO111MODULE: on
      TARGET: amd64
      
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      
      - name: Install multus and kubectl
        run: |
          go get -u golang.org/x/lint/golint 
          ./hack/install-kubebuilder-tools.sh 
          git clone https://github.com/intel/multus-cni.git
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
      
      - name: Install and configure KIND
        run: |
          GO111MODULE="on" go get sigs.k8s.io/kind@v0.8.1
          echo testprint1
          sudo bash -c "echo ‘export PATH=/root/go/bin:$PATH’ >> /root/.bashrc"
          echo testprint2
          sudo source .bashrc
          echo testprint3
          cat > kind-flannel.yml << EOF
          kind: Cluster
          apiVersion: kind.sigs.k8s.io/v1alpha3
          networking:
          disableDefaultCNI: true # disable kindnet
          podSubnet: 10.244.0.0/16 # set to Flannel's default subnet
          Nodes:
          - role: control-plane
          - role: worker
          - role: worker
          EOF
          echotestprint4
          kind create cluster --config kind-flannel.yml
    
      - name: Explore working directory (temporary)
        run: |
          pwd
          echo ---
          ls
          echo ---
          echo $GOPATH
